2024-07-01 10:22:39,770 - ERROR - An error occurred: 'GDriveHandler' object has no attribute 'check_lock_file'
2024-07-01 10:22:48,953 - ERROR - An error occurred: 'GDriveHandler' object has no attribute 'check_lock_file'
2024-07-01 10:25:55,001 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-07-01 10:25:55,005 - INFO - Authentication successful.
2024-07-01 10:25:55,008 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json
2024-07-01 10:25:55,503 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable
2024-07-01 10:25:56,953 - INFO - Lock file created.
2024-07-01 10:25:56,953 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json
2024-07-01 10:25:58,936 - ERROR - An error occurred: [Errno 13] Permission denied: 'test_from_gdrive.xlsx'
2024-07-01 10:25:58,936 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json
2024-07-01 10:25:59,370 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1HFOHrehtS1laostVsljNnUSoqtmfHDZ4?
2024-07-01 10:25:59,970 - INFO - Lock file deleted.
2024-07-01 10:41:17,103 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-07-01 10:41:17,103 - INFO - Authentication successful.
2024-07-01 10:41:17,120 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json
2024-07-01 10:41:17,653 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable
2024-07-01 10:41:19,170 - INFO - Lock file created.
2024-07-01 10:41:19,187 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json
2024-07-01 10:41:21,103 - INFO - File test_from_gdrive.xlsx downloaded.
2024-07-01 10:41:21,120 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json
2024-07-01 10:41:21,534 - DEBUG - URL being requested: PATCH https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json
2024-07-01 10:41:22,458 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json
2024-07-01 10:41:22,870 - INFO - File renamed to Students_Detail_Report_2023.xlsx.
2024-07-01 10:41:22,870 - ERROR - An error occurred: [Errno 2] No such file or directory: 'c:\\Users\\msenthilnathan\\chatGPT-GUI\\Nool 2.0\\data\\data/status.xlsx'
2024-07-01 10:41:22,886 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json
2024-07-01 10:41:23,337 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1Pz0-1f2NqPcDIlMNNr_gvdrUmlJoEf81?
2024-07-01 10:41:24,237 - INFO - Lock file deleted.
2024-07-01 10:48:12,903 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-07-01 10:48:12,903 - INFO - Authentication successful.
2024-07-01 10:48:12,903 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json
2024-07-01 10:48:13,370 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable
2024-07-01 10:48:14,770 - INFO - Lock file created.
2024-07-01 10:48:14,770 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json
2024-07-01 10:48:16,803 - ERROR - An error occurred: [Errno 13] Permission denied: 'test_from_gdrive.xlsx'
2024-07-01 10:48:16,803 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json
2024-07-01 10:48:17,233 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/11e_J_tiUmJOus6bv_cX-ZKMCI44KlWDv?
2024-07-01 10:48:17,837 - INFO - Lock file deleted.
2024-07-01 14:53:57,153 - INFO - access_token is expired. Now: 2024-07-01 18:53:57.153591, token_expiry: 2024-07-01 15:18:14
2024-07-01 14:53:57,153 - INFO - Refreshing access_token
2024-07-01 14:53:57,591 - INFO - Authentication successful.
2024-07-01 14:53:57,598 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-07-01 14:53:57,604 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json
2024-07-01 14:53:58,052 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable
2024-07-01 14:53:59,667 - INFO - Lock file created.
2024-07-01 14:53:59,677 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json
2024-07-01 14:54:01,487 - ERROR - An error occurred: [Errno 13] Permission denied: 'test_from_gdrive.xlsx'
2024-07-01 14:54:01,491 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json
2024-07-01 14:54:01,936 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1F0H6FAUfin5da_WjoLfs2XEzuGWs_gwE?
2024-07-01 14:54:02,580 - INFO - Lock file deleted.
2024-07-01 14:55:22,537 - INFO - Successfully retrieved access token
2024-07-01 14:55:22,547 - INFO - file_cache is only supported with oauth2client<4.0.0
2024-07-01 14:55:22,553 - INFO - Authentication successful.
2024-07-01 14:55:22,553 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json
2024-07-01 14:55:23,003 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable
2024-07-01 14:55:24,330 - INFO - Lock file created.
2024-07-01 14:55:24,340 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json
2024-07-01 14:55:26,162 - ERROR - An error occurred: [Errno 13] Permission denied: 'test_from_gdrive.xlsx'
2024-07-01 14:55:26,165 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json
2024-07-01 14:55:26,616 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1h1_LLIryhy1YstfAFMZezGMDYz0rJeOD?
2024-07-01 14:55:27,264 - INFO - Lock file deleted.
2024-07-01 15:02:29,180 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-01 15:02:29,180 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:66
2024-07-01 15:02:29,187 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:02:29,683 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:02:31,215 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:87
2024-07-01 15:02:31,228 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:02:32,683 - ERROR - An error occurred: [Errno 13] Permission denied: 'test_from_gdrive.xlsx' - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_main.py:69
2024-07-01 15:02:32,691 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:02:33,106 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1gU29VcLSWlfK8f7u5a_UjZZTeN7f_p6e? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:02:33,736 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:94
2024-07-01 15:05:04,037 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-01 15:05:04,047 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:66
2024-07-01 15:05:04,047 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:05:04,477 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:05:05,908 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:87
2024-07-01 15:05:05,918 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:05:07,261 - ERROR - An error occurred: [Errno 13] Permission denied: 'test_from_gdrive.xlsx' - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_main.py:69
Traceback (most recent call last):
  File "c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_main.py", line 54, in <module>
    gdrive_handler.download_file(file_id_to_download, file_name_to_download)
  File "c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py", line 98, in download_file
    file.GetContentFile(file_name)
  File "C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pydrive\files.py", line 211, in GetContentFile
    f = open(filename, 'wb')
        ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'test_from_gdrive.xlsx'
2024-07-01 15:05:07,270 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:05:07,781 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1DlOKAaitmKgJBH71LuloGi2_HQdibAhP? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:05:08,413 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:94
2024-07-01 15:10:08,986 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-01 15:10:08,986 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:66
2024-07-01 15:10:09,002 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:10:09,520 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:10:10,853 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:87
2024-07-01 15:10:10,853 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:10:12,154 - ERROR - An error occurred: [Errno 13] Permission denied: 'test_from_gdrive.xlsx' - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_main.py:69
Traceback (most recent call last):
  File "c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_main.py", line 54, in <module>
    gdrive_handler.download_file(file_id_to_download, file_name_to_download)
  File "c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py", line 98, in download_file
    file.GetContentFile(file_name)
  File "C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pydrive\files.py", line 211, in GetContentFile
    f = open(filename, 'wb')
        ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'test_from_gdrive.xlsx'
2024-07-01 15:10:12,154 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:10:12,586 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1cVZ8iKqNcoT5zvvRptqV3yySczZ-8JfL? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:10:13,242 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:94
2024-07-01 15:11:20,553 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-01 15:11:20,553 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:66
2024-07-01 15:11:20,570 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:11:21,017 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:11:22,403 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:87
2024-07-01 15:11:22,405 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:11:23,870 - ERROR - An error occurred: [Errno 13] Permission denied: 'test_from_gdrive.xlsx' - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_main.py:69
Traceback (most recent call last):
  File "c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_main.py", line 54, in <module>
    gdrive_handler.download_file(file_id_to_download, file_name_to_download)
  File "c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py", line 98, in download_file
    file.GetContentFile(file_name)
  File "C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pydrive\files.py", line 211, in GetContentFile
    f = open(filename, 'wb')
        ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'test_from_gdrive.xlsx'
2024-07-01 15:11:23,870 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:11:24,309 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1Z5SNLzQFwSJ8ooZZb9KpJl1MWM3KcJqa? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:11:24,953 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:94
2024-07-01 15:17:35,470 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-01 15:17:35,470 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:66
2024-07-01 15:17:35,470 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:17:35,965 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:17:37,552 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:87
2024-07-01 15:17:37,553 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:17:38,770 - ERROR - An error occurred: [Errno 13] Permission denied: 'test_from_gdrive.xlsx' - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_main.py:71
Traceback (most recent call last):
  File "c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_main.py", line 56, in <module>
    gdrive_handler.download_file(file_id_to_download, file_name_to_download)
  File "c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py", line 98, in download_file
    file.GetContentFile(file_name)
  File "C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pydrive\files.py", line 211, in GetContentFile
    f = open(filename, 'wb')
        ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'test_from_gdrive.xlsx'
2024-07-01 15:17:38,786 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:17:39,238 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1YobjF_-BYUE7u67zna76QoDi-uIqnZfo? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:17:39,853 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:94
2024-07-01 15:20:54,353 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-01 15:20:54,353 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:66
2024-07-01 15:20:54,353 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:20:54,798 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:20:56,186 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:87
2024-07-01 15:20:56,186 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:20:58,074 - INFO - File test_from_gdrive.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:99
2024-07-01 15:20:58,090 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:20:58,490 - DEBUG - URL being requested: PATCH https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:20:59,087 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:20:59,603 - INFO - File renamed to Students_Detail_Report_2023.xlsx. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:106
2024-07-01 15:20:59,703 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:21:01,052 - INFO - File status.xlsx uploaded to Drive. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:112
2024-07-01 15:21:01,052 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:21:01,497 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1eEiTmF377rVUQz6HSzlOM7yvqNUPJYoV? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-01 15:21:02,133 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:94
2024-07-02 08:29:33,704 - INFO - access_token is expired. Now: 2024-07-02 12:29:33.704938, token_expiry: 2024-07-01 19:55:21 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-02 08:29:33,704 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-02 08:29:34,175 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:66
2024-07-02 08:29:34,175 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 08:29:34,197 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 08:29:34,854 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 08:29:36,474 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:87
2024-07-02 08:29:36,481 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 08:29:39,190 - INFO - File test_from_gdrive.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:99
2024-07-02 08:29:39,205 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 08:29:40,229 - DEBUG - URL being requested: PATCH https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 08:29:41,480 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 08:29:42,080 - INFO - File renamed to Students_Detail_Report_2023.xlsx. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:106
2024-07-02 08:29:42,173 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 08:29:43,601 - INFO - File status.xlsx uploaded to Drive. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:112
2024-07-02 08:29:43,601 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 08:29:44,202 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1XMR-WikLCjfjm70J06ENne7K0jDtWY6U? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 08:29:45,202 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:94
2024-07-02 08:46:42,993 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 08:46:42,993 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 08:46:43,003 - DEBUG - URL being requested: GET https://www.googleapis.com/oauth2/v2/userinfo?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 08:46:43,398 - INFO - Refreshing due to a 401 (attempt 1/2) - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\transport.py:183
2024-07-02 08:46:43,402 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-02 08:46:43,853 - INFO - Refreshing due to a 401 (attempt 2/2) - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\transport.py:183
2024-07-02 08:46:43,863 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-02 08:46:44,023 - ERROR - Authentication failed: <HttpError 401 when requesting https://www.googleapis.com/oauth2/v2/userinfo?alt=json returned "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.". Details: "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."> - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:73
2024-07-02 08:51:56,686 - INFO - Successfully retrieved access token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:2074
2024-07-02 08:51:56,696 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 08:51:56,696 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 08:51:56,696 - DEBUG - URL being requested: GET https://www.googleapis.com/oauth2/v2/userinfo?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 08:51:57,107 - INFO - Refreshing due to a 401 (attempt 1/2) - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\transport.py:183
2024-07-02 08:51:57,107 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-02 08:51:57,564 - INFO - Refreshing due to a 401 (attempt 2/2) - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\transport.py:183
2024-07-02 08:51:57,564 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-02 08:51:57,699 - ERROR - Authentication failed: <HttpError 401 when requesting https://www.googleapis.com/oauth2/v2/userinfo?alt=json returned "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.". Details: "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."> - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:73
2024-07-02 08:56:42,006 - INFO - Successfully retrieved access token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:2074
2024-07-02 08:56:42,016 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 08:56:42,016 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 08:56:42,026 - DEBUG - URL being requested: GET https://www.googleapis.com/oauth2/v2/userinfo?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 08:56:42,407 - INFO - Refreshing credentials due to a 401 response. Attempt 1/2. - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google_auth_httplib2.py:238
2024-07-02 08:56:42,407 - DEBUG - Making request: POST https://oauth2.googleapis.com/token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google_auth_httplib2.py:118
2024-07-02 08:56:42,875 - INFO - Refreshing credentials due to a 401 response. Attempt 2/2. - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google_auth_httplib2.py:238
2024-07-02 08:56:42,875 - DEBUG - Making request: POST https://oauth2.googleapis.com/token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google_auth_httplib2.py:118
2024-07-02 08:56:43,011 - ERROR - Authentication failed: <HttpError 401 when requesting https://www.googleapis.com/oauth2/v2/userinfo?alt=json returned "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.". Details: "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."> - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:74
2024-07-02 08:59:32,713 - INFO - Successfully retrieved access token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:2074
2024-07-02 08:59:32,713 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 08:59:32,713 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 08:59:32,729 - DEBUG - URL being requested: GET https://www.googleapis.com/oauth2/v2/userinfo?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 08:59:33,082 - INFO - Refreshing credentials due to a 401 response. Attempt 1/2. - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google_auth_httplib2.py:238
2024-07-02 08:59:33,083 - DEBUG - Making request: POST https://oauth2.googleapis.com/token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google_auth_httplib2.py:118
2024-07-02 08:59:33,541 - INFO - Refreshing credentials due to a 401 response. Attempt 2/2. - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google_auth_httplib2.py:238
2024-07-02 08:59:33,541 - DEBUG - Making request: POST https://oauth2.googleapis.com/token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google_auth_httplib2.py:118
2024-07-02 08:59:33,690 - ERROR - Authentication failed: <HttpError 401 when requesting https://www.googleapis.com/oauth2/v2/userinfo?alt=json returned "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.". Details: "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."> - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:75
2024-07-02 09:04:46,056 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 09:04:46,056 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 09:04:46,056 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 09:04:46,071 - DEBUG - URL being requested: GET https://www.googleapis.com/oauth2/v2/userinfo?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 09:04:46,471 - INFO - Refreshing credentials due to a 401 response. Attempt 1/2. - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google_auth_httplib2.py:238
2024-07-02 09:04:46,471 - DEBUG - Making request: POST https://oauth2.googleapis.com/token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google_auth_httplib2.py:118
2024-07-02 09:04:47,040 - INFO - Refreshing credentials due to a 401 response. Attempt 2/2. - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google_auth_httplib2.py:238
2024-07-02 09:04:47,040 - DEBUG - Making request: POST https://oauth2.googleapis.com/token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google_auth_httplib2.py:118
2024-07-02 09:04:47,198 - ERROR - Authentication failed: <HttpError 401 when requesting https://www.googleapis.com/oauth2/v2/userinfo?alt=json returned "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.". Details: "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."> - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:78
2024-07-02 09:05:25,875 - INFO - Successfully retrieved access token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:2074
2024-07-02 09:05:25,875 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 09:05:25,895 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 09:05:25,897 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 09:05:25,897 - DEBUG - URL being requested: GET https://www.googleapis.com/oauth2/v2/userinfo?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 09:05:26,254 - INFO - Refreshing credentials due to a 401 response. Attempt 1/2. - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google_auth_httplib2.py:238
2024-07-02 09:05:26,254 - DEBUG - Making request: POST https://oauth2.googleapis.com/token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google_auth_httplib2.py:118
2024-07-02 09:05:26,693 - INFO - Refreshing credentials due to a 401 response. Attempt 2/2. - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google_auth_httplib2.py:238
2024-07-02 09:05:26,693 - DEBUG - Making request: POST https://oauth2.googleapis.com/token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\google_auth_httplib2.py:118
2024-07-02 09:05:26,856 - ERROR - Authentication failed: <HttpError 401 when requesting https://www.googleapis.com/oauth2/v2/userinfo?alt=json returned "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.". Details: "Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."> - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:78
2024-07-02 09:08:11,468 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 09:08:11,483 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 09:08:11,483 - DEBUG - URL being requested: GET https://www.googleapis.com/oauth2/v2/userinfo?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 09:08:11,891 - INFO - Refreshing due to a 401 (attempt 1/2) - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\transport.py:183
2024-07-02 09:08:11,892 - ERROR - Authentication failed: The access_token is expired or invalid and can't be refreshed. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:78
2024-07-02 09:08:35,344 - INFO - Successfully retrieved access token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:2074
2024-07-02 09:08:35,360 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 09:08:35,378 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 09:08:35,380 - DEBUG - URL being requested: GET https://www.googleapis.com/oauth2/v2/userinfo?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 09:08:35,723 - INFO - Refreshing due to a 401 (attempt 1/2) - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\transport.py:183
2024-07-02 09:08:35,723 - ERROR - Authentication failed: The access_token is expired or invalid and can't be refreshed. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:78
2024-07-02 09:11:11,268 - INFO - Successfully retrieved access token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:2074
2024-07-02 09:11:11,285 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 09:11:11,285 - INFO - Access token: ya29.a0AXooCgttyg-wygHOqTaWdyk7KPjgKKjBnuZ80CEK7ovlTwQt0JUAABQeuAIugoVdz0mA7InBtd0RsUthhA0CnvAXJRbXjgvX5qgpvF9EklAAbaXJqRwlHGmgtrn2UR_CKOAadQwnLREz7ZaNAvibWY1kCIVIRp1b0MRHaCgYKAVMSARESFQHGX2MiPJ34hdq1bAzn4b2oGrvLBw0171 - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-02 09:11:11,285 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 09:11:11,285 - DEBUG - URL being requested: GET https://www.googleapis.com/oauth2/v2/userinfo?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 09:11:11,633 - INFO - Refreshing due to a 401 (attempt 1/2) - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\transport.py:183
2024-07-02 09:11:11,633 - ERROR - Authentication failed: The access_token is expired or invalid and can't be refreshed. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:78
2024-07-02 09:13:46,221 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 09:13:46,221 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:75
2024-07-02 09:13:46,221 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 09:13:46,786 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 09:13:48,341 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:125
2024-07-02 09:13:48,341 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 09:13:50,264 - INFO - File test_from_gdrive.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:137
2024-07-02 09:13:50,264 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 09:13:50,750 - DEBUG - URL being requested: PATCH https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 09:13:51,335 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 09:13:51,799 - INFO - File renamed to Students_Detail_Report_2023.xlsx. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:144
2024-07-02 09:13:51,891 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 09:13:53,486 - INFO - File status.xlsx uploaded to Drive. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:150
2024-07-02 09:13:53,502 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 09:13:54,002 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1OkUj9uBbWYSvDQ9-zitAopsXnwa3G1Y6? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 09:13:54,690 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:132
2024-07-02 12:45:45,884 - INFO - access_token is expired. Now: 2024-07-02 16:45:45.884544, token_expiry: 2024-07-02 14:11:10 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-02 12:45:45,884 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-02 12:45:46,369 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:75
2024-07-02 12:45:46,373 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 12:45:46,380 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:45:46,931 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:45:48,524 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:125
2024-07-02 12:45:48,546 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:45:50,454 - INFO - File test_from_gdrive.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:137
2024-07-02 12:45:50,469 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:45:50,940 - DEBUG - URL being requested: PATCH https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:45:51,642 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:45:52,144 - INFO - File renamed to Students_Detail_Report_2023.xlsx. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:144
2024-07-02 12:45:52,233 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:45:53,716 - INFO - File status.xlsx uploaded to Drive. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:150
2024-07-02 12:45:53,732 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:45:54,296 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1q3vrTND9vXveqbIclB91otgv3VZsI8__? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:45:54,971 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:132
2024-07-02 12:48:09,845 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 12:48:09,845 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:75
2024-07-02 12:48:09,845 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:48:10,330 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:48:11,818 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:118
2024-07-02 12:48:11,818 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:48:13,693 - INFO - File test_from_gdrive.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:130
2024-07-02 12:48:13,697 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:48:14,144 - DEBUG - URL being requested: PATCH https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:48:14,717 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:48:15,178 - INFO - File renamed to Students_Detail_Report_2023.xlsx. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:138
2024-07-02 12:48:15,283 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:48:16,605 - INFO - File status.xlsx uploaded to Drive. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:144
2024-07-02 12:48:16,621 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:48:17,139 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1dl4Rue_hbXcrVWpAb4BALpHp4HGCtQYx? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:48:17,810 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:125
2024-07-02 12:51:05,917 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 12:51:05,933 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:75
2024-07-02 12:51:05,933 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:51:06,448 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:51:07,804 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:118
2024-07-02 12:51:07,812 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:51:09,230 - INFO - File test_from_gdrive.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:130
2024-07-02 12:51:09,230 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?fields=title&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:51:09,661 - INFO - Original file name: Students_Detail_Report_2023.xlsx - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:139
2024-07-02 12:51:09,676 - DEBUG - URL being requested: PATCH https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?supportsAllDrives=true&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:51:10,484 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?fields=title&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:51:10,917 - INFO - File renamed to test_name_after_rename. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:147
2024-07-02 12:51:11,016 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:51:12,266 - INFO - File status.xlsx uploaded to Drive. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:155
2024-07-02 12:51:12,266 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:51:12,833 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1YnX5w8T0iudDr2frAebsoDYJPcs0hzF3? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 12:51:13,492 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:125
2024-07-02 13:01:11,624 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 13:01:11,639 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:75
2024-07-02 13:01:11,639 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:01:13,158 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:01:14,534 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:118
2024-07-02 13:01:14,534 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:01:16,267 - INFO - File test_from_gdrive.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:130
2024-07-02 13:01:16,267 - ERROR - An error occurred: 'GDriveHandler' object has no attribute 'check_and_download_file' - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_main.py:83
Traceback (most recent call last):
  File "c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_main.py", line 68, in <module>
    gdrive_handler.check_and_download_file(file_id_to_download, file_name_to_download)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GDriveHandler' object has no attribute 'check_and_download_file'
2024-07-02 13:01:16,267 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:01:16,752 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1qteRUM5VUcNaJFnrXNkUtWze7UsvHEve? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:01:17,438 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:125
2024-07-02 13:05:05,899 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 13:05:05,911 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:76
2024-07-02 13:05:05,911 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:05:06,417 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:05:07,814 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:119
2024-07-02 13:05:07,832 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:05:09,751 - INFO - File test_from_gdrive.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:131
2024-07-02 13:05:09,751 - ERROR - An error occurred: module 'datetime' has no attribute 'fromtimestamp' - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_main.py:83
Traceback (most recent call last):
  File "c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_main.py", line 68, in <module>
    gdrive_handler.check_and_download_file(file_id_to_download, file_name_to_download)
  File "c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py", line 138, in check_and_download_file
    local_mod_time = datetime.fromtimestamp(os.path.getmtime(local_path), tz=datetime.timezone.utc)
                     ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'fromtimestamp'
2024-07-02 13:05:09,767 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:05:10,252 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/13shzacG491P07bZJuhUQcOT4mHiOfYq4? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:05:10,951 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:126
2024-07-02 13:06:46,350 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 13:06:46,350 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:76
2024-07-02 13:06:46,350 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:06:46,851 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:06:48,184 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:119
2024-07-02 13:06:48,201 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:06:49,688 - INFO - File test_from_gdrive.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:131
2024-07-02 13:06:49,688 - ERROR - An error occurred: type object 'datetime.datetime' has no attribute 'timezone' - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_main.py:83
Traceback (most recent call last):
  File "c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_main.py", line 68, in <module>
    gdrive_handler.check_and_download_file(file_id_to_download, file_name_to_download)
  File "c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py", line 138, in check_and_download_file
    local_mod_time = datetime.fromtimestamp(os.path.getmtime(local_path), tz=datetime.timezone.utc)
                                                                             ^^^^^^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'timezone'. Did you mean: 'astimezone'?
2024-07-02 13:06:49,710 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:06:50,189 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1P-gH-te9hgOo5yZAsyjgInZwH0j4ZpFs? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:06:50,943 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:126
2024-07-02 13:10:06,577 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 13:10:06,577 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:77
2024-07-02 13:10:06,577 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:10:07,109 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:10:08,511 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:120
2024-07-02 13:10:08,511 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:10:10,584 - INFO - File test_from_gdrive.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:132
2024-07-02 13:10:10,584 - INFO - Local file modification time (UTC): 2024-07-02 17:10:10.568729+00:00 - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:140
2024-07-02 13:10:10,584 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?fields=modifiedDate&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:10:11,032 - INFO - Google Drive file modification time (UTC): 2024-07-02 16:51:10.514000+00:00 - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:150
2024-07-02 13:10:11,032 - INFO - No need to download. The local file is up-to-date. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:157
2024-07-02 13:10:11,032 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?fields=title&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:10:11,501 - INFO - Original file name: test_name_after_rename - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:167
2024-07-02 13:10:11,501 - DEBUG - URL being requested: PATCH https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?supportsAllDrives=true&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:10:12,351 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?fields=title&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:10:12,758 - INFO - File renamed to test_name_after_rename. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:175
2024-07-02 13:10:12,850 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:10:14,229 - INFO - File status.xlsx uploaded to Drive. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:183
2024-07-02 13:10:14,245 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:10:14,742 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1nD0Y4l473SkmxW4SS-SmAfGv8SGHPo5A? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 13:10:15,366 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:127
2024-07-02 15:28:28,965 - INFO - access_token is expired. Now: 2024-07-02 19:28:28.965111, token_expiry: 2024-07-02 17:45:45 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-02 15:28:28,965 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-02 15:28:29,219 - INFO - access_token is expired. Now: 2024-07-02 19:28:29.219603, token_expiry: 2024-07-02 17:45:45 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-02 15:28:29,219 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-02 15:28:29,219 - ERROR - Authentication failed: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:80
2024-07-02 15:37:50,818 - INFO - access_token is expired. Now: 2024-07-02 19:37:50.818002, token_expiry: 2024-07-02 17:45:45 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-02 15:37:50,818 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-02 15:37:51,072 - INFO - access_token is expired. Now: 2024-07-02 19:37:51.072867, token_expiry: 2024-07-02 17:45:45 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-02 15:37:51,072 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-02 15:37:51,072 - ERROR - Authentication failed: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:80
2024-07-02 15:38:15,115 - INFO - access_token is expired. Now: 2024-07-02 19:38:15.115630, token_expiry: 2024-07-02 17:45:45 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-02 15:38:15,115 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-02 15:38:15,362 - INFO - access_token is expired. Now: 2024-07-02 19:38:15.362427, token_expiry: 2024-07-02 17:45:45 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-02 15:38:15,362 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-02 15:38:15,362 - ERROR - Authentication failed: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:80
2024-07-02 15:40:49,780 - INFO - access_token is expired. Now: 2024-07-02 19:40:49.780344, token_expiry: 2024-07-02 17:45:45 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-02 15:40:49,780 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-02 15:40:50,049 - INFO - access_token is expired. Now: 2024-07-02 19:40:50.049911, token_expiry: 2024-07-02 17:45:45 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-02 15:40:50,049 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-02 15:40:50,049 - ERROR - Authentication failed: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:89
2024-07-02 15:40:50,049 - ERROR - An error occurred: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:26
2024-07-02 15:40:50,049 - ERROR - An error occurred: 'GDriveHandler' object has no attribute 'drive' - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_main.py:86
Traceback (most recent call last):
  File "c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_main.py", line 54, in <module>
    if gdrive_handler.check_lock_file(folder_id, 'process.lock'):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py", line 122, in check_lock_file
    file_list = self.drive.ListFile({'q': query}).GetList()
                ^^^^^^^^^^
AttributeError: 'GDriveHandler' object has no attribute 'drive'
2024-07-02 15:42:00,628 - INFO - access_token is expired. Now: 2024-07-02 19:42:00.628305, token_expiry: 2024-07-02 17:45:45 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-02 15:42:00,630 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-02 15:42:00,880 - INFO - access_token is expired. Now: 2024-07-02 19:42:00.880906, token_expiry: 2024-07-02 17:45:45 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-02 15:42:00,880 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-02 15:42:00,880 - ERROR - Authentication failed: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:89
2024-07-02 15:42:07,014 - ERROR - An error occurred: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:26
2024-07-02 15:44:04,795 - INFO - access_token is expired. Now: 2024-07-02 19:44:04.795848, token_expiry: 2024-07-02 17:45:45 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-02 15:44:04,795 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-02 15:44:05,234 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-02 15:44:46,783 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 15:44:46,783 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-02 15:45:16,907 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 15:45:16,907 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-02 19:24:07,834 - INFO - Successfully retrieved access token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:2074
2024-07-02 19:24:07,840 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 19:24:07,840 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-02 19:24:07,861 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:24:08,341 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:24:10,750 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:129
2024-07-02 19:24:10,765 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:24:11,228 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:24:11,713 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1H7Q4sM3meNrmVYYqeN5O_8hki5wabYWp? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:24:12,470 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:136
2024-07-02 19:31:22,387 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 19:31:22,387 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-02 19:31:22,403 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:31:23,121 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:31:25,032 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:129
2024-07-02 19:31:25,042 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1o3QSwnuXZbdJHK2E4iazw7FA5HF4q5sr?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:31:27,050 - INFO - File student.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:141
2024-07-02 19:31:27,054 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:31:27,546 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1bva6ZV65kdEINENYIydoOtdSJftTJ62M? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:31:28,195 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:136
2024-07-02 19:35:24,072 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 19:35:24,072 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-02 19:35:24,087 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:35:24,574 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:35:25,998 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:129
2024-07-02 19:35:26,014 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1o3QSwnuXZbdJHK2E4iazw7FA5HF4q5sr?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:35:27,501 - INFO - File data\student.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:141
2024-07-02 19:35:27,513 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:35:28,002 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1fJcbFT4e1411jj4_sPMfOLM08XHboYW3? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:35:28,658 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:136
2024-07-02 19:36:02,853 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 19:36:02,853 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-02 19:36:02,853 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:36:03,326 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:36:04,886 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:129
2024-07-02 19:36:04,886 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1o3QSwnuXZbdJHK2E4iazw7FA5HF4q5sr?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:36:06,457 - INFO - File data\students.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:141
2024-07-02 19:36:06,476 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:36:07,024 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/15PaY0aktz2EKdhDdcS-Mmi3GIULefdhz? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:36:07,656 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:136
2024-07-02 19:38:04,130 - INFO - Successfully retrieved access token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:2074
2024-07-02 19:38:04,146 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 19:38:04,146 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-02 19:38:04,146 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:38:04,650 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:38:05,960 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:129
2024-07-02 19:38:05,976 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1o3QSwnuXZbdJHK2E4iazw7FA5HF4q5sr?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:38:07,711 - INFO - File data\students.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:141
2024-07-02 19:38:07,714 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:38:08,236 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1bDuVwGgWLiyP5lWWYIo3e8gNb-eAGMft? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:38:08,852 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:136
2024-07-02 19:38:25,235 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 19:38:25,250 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-02 19:38:25,250 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:38:25,721 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:38:27,159 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:129
2024-07-02 19:38:27,159 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1o3QSwnuXZbdJHK2E4iazw7FA5HF4q5sr?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:38:28,666 - INFO - File data\students.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:141
2024-07-02 19:38:28,682 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:38:29,152 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1oKhNV20WjpeV4EjUM6csAGf4OU2f066w? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:38:29,833 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:136
2024-07-02 19:40:02,367 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-02 19:40:02,367 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-02 19:40:02,367 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:40:02,868 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:40:04,156 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:129
2024-07-02 19:40:04,156 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1o3QSwnuXZbdJHK2E4iazw7FA5HF4q5sr?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:40:05,575 - INFO - File data\students.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:141
2024-07-02 19:40:05,582 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:40:06,045 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1oKsH3rc133oO-lnRrVrtTy4USAxD5d4S? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-02 19:40:06,682 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:136
2024-07-04 18:06:54,701 - INFO - access_token is expired. Now: 2024-07-04 22:06:54.701073, token_expiry: 2024-07-03 00:38:03 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-04 18:06:54,701 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-04 18:06:55,097 - INFO - access_token is expired. Now: 2024-07-04 22:06:55.097155, token_expiry: 2024-07-03 00:38:03 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-04 18:06:55,097 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-04 18:06:55,097 - ERROR - Authentication failed: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:89
2024-07-04 18:06:55,097 - ERROR - An error occurred: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:26
2024-07-04 18:08:15,657 - INFO - access_token is expired. Now: 2024-07-04 22:08:15.657404, token_expiry: 2024-07-03 00:38:03 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-04 18:08:15,657 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-04 18:08:16,009 - INFO - access_token is expired. Now: 2024-07-04 22:08:16.009580, token_expiry: 2024-07-03 00:38:03 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-04 18:08:16,025 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-04 18:08:16,025 - ERROR - Authentication failed: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:89
2024-07-04 18:08:16,026 - ERROR - An error occurred: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:26
2024-07-04 18:11:14,216 - INFO - access_token is expired. Now: 2024-07-04 22:11:14.216119, token_expiry: 2024-07-03 00:38:03 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-04 18:11:14,216 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-04 18:11:14,582 - INFO - access_token is expired. Now: 2024-07-04 22:11:14.582410, token_expiry: 2024-07-03 00:38:03 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-04 18:11:14,582 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-04 18:11:14,582 - ERROR - Authentication failed: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:89
2024-07-04 18:11:14,582 - ERROR - An error occurred: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:26
2024-07-04 21:21:59,442 - INFO - access_token is expired. Now: 2024-07-05 01:21:59.442045, token_expiry: 2024-07-03 00:38:03 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-04 21:21:59,442 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-04 21:21:59,794 - INFO - access_token is expired. Now: 2024-07-05 01:21:59.794482, token_expiry: 2024-07-03 00:38:03 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-04 21:21:59,798 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-04 21:21:59,798 - ERROR - Authentication failed: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:89
2024-07-04 21:21:59,802 - ERROR - An error occurred: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:26
2024-07-04 21:27:49,096 - INFO - access_token is expired. Now: 2024-07-05 01:27:49.096522, token_expiry: 2024-07-03 00:38:03 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-04 21:27:49,096 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-04 21:27:49,455 - INFO - access_token is expired. Now: 2024-07-05 01:27:49.455167, token_expiry: 2024-07-03 00:38:03 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-04 21:27:49,455 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-04 21:27:49,455 - ERROR - Authentication failed: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:89
2024-07-04 21:27:49,455 - ERROR - An error occurred: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:26
2024-07-04 21:29:11,026 - INFO - access_token is expired. Now: 2024-07-05 01:29:11.026064, token_expiry: 2024-07-03 00:38:03 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-04 21:29:11,026 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-04 21:29:11,376 - INFO - access_token is expired. Now: 2024-07-05 01:29:11.376349, token_expiry: 2024-07-03 00:38:03 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-04 21:29:11,392 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-04 21:29:11,392 - ERROR - Authentication failed: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:89
2024-07-04 21:29:11,392 - ERROR - An error occurred: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:26
2024-07-04 21:37:37,327 - INFO - access_token is expired. Now: 2024-07-05 01:37:37.327361, token_expiry: 2024-07-03 00:38:03 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-04 21:37:37,327 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-04 21:37:37,695 - INFO - access_token is expired. Now: 2024-07-05 01:37:37.695529, token_expiry: 2024-07-03 00:38:03 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-04 21:37:37,695 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-04 21:37:37,695 - ERROR - Authentication failed: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:89
2024-07-04 21:37:37,695 - ERROR - An error occurred: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:26
2024-07-04 21:38:14,422 - INFO - access_token is expired. Now: 2024-07-05 01:38:14.422269, token_expiry: 2024-07-03 00:38:03 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-04 21:38:14,422 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-04 21:38:14,770 - INFO - access_token is expired. Now: 2024-07-05 01:38:14.770060, token_expiry: 2024-07-03 00:38:03 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-04 21:38:14,770 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-04 21:38:14,770 - ERROR - Authentication failed: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:89
2024-07-04 21:38:14,770 - ERROR - An error occurred: Unable to find the server at oauth2.googleapis.com - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:26
2024-07-31 21:36:58,473 - INFO - access_token is expired. Now: 2024-08-01 01:36:58.473791, token_expiry: 2024-07-03 00:38:03 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-07-31 21:36:58,473 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-31 21:36:58,936 - INFO - Failed to retrieve access token: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
} - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:806
2024-07-31 21:36:58,936 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-31 21:36:59,056 - INFO - Failed to retrieve access token: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
} - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:806
2024-07-31 21:36:59,058 - ERROR - Authentication failed: Access token refresh failed: invalid_grant: Bad Request - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:89
2024-07-31 21:36:59,058 - ERROR - An error occurred: Access token refresh failed: invalid_grant: Bad Request - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:26
2024-07-31 21:43:47,807 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-31 21:43:48,209 - INFO - Failed to retrieve access token: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
} - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:806
2024-07-31 21:43:48,209 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-31 21:43:48,294 - INFO - Failed to retrieve access token: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
} - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:806
2024-07-31 21:43:48,294 - ERROR - Authentication failed: Access token refresh failed: invalid_grant: Bad Request - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:89
2024-07-31 21:43:48,294 - ERROR - An error occurred: Access token refresh failed: invalid_grant: Bad Request - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:26
2024-07-31 21:47:53,443 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-31 21:47:53,877 - INFO - Failed to retrieve access token: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
} - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:806
2024-07-31 21:47:53,877 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-31 21:47:53,960 - INFO - Failed to retrieve access token: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
} - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:806
2024-07-31 21:47:53,960 - ERROR - Authentication failed: Access token refresh failed: invalid_grant: Bad Request - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:89
2024-07-31 21:47:53,960 - ERROR - An error occurred: Access token refresh failed: invalid_grant: Bad Request - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:26
2024-07-31 21:49:21,130 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-31 21:49:21,516 - INFO - Failed to retrieve access token: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
} - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:806
2024-07-31 21:49:21,532 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-07-31 21:49:21,610 - INFO - Failed to retrieve access token: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
} - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:806
2024-07-31 21:49:21,610 - ERROR - Authentication failed: Access token refresh failed: invalid_grant: Bad Request - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:89
2024-07-31 21:52:48,360 - INFO - Successfully retrieved access token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:2074
2024-07-31 21:52:48,391 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-31 21:52:48,397 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-31 21:52:48,397 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:52:48,962 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:52:50,570 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:129
2024-07-31 21:52:50,586 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1o3QSwnuXZbdJHK2E4iazw7FA5HF4q5sr?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:52:52,498 - INFO - File students.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:141
2024-07-31 21:52:52,499 - INFO - Local file modification time (UTC): 2024-08-01 01:52:52.487592+00:00 - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:149
2024-07-31 21:52:52,503 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1o3QSwnuXZbdJHK2E4iazw7FA5HF4q5sr?fields=modifiedDate&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:52:52,936 - INFO - Google Drive file modification time (UTC): 2024-06-30 17:43:36+00:00 - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:159
2024-07-31 21:52:52,936 - INFO - No need to download. The local file is up-to-date. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:166
2024-07-31 21:52:52,941 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?fields=title&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:52:53,397 - INFO - Original file name: test_name_after_rename - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:176
2024-07-31 21:52:53,397 - DEBUG - URL being requested: PATCH https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?supportsAllDrives=true&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:52:54,284 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?fields=title&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:52:54,748 - INFO - File renamed to test_name_after_rename. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:184
2024-07-31 21:52:54,843 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:52:56,381 - INFO - File status.xlsx uploaded to Drive. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:192
2024-07-31 21:52:56,388 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:52:56,889 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1sTLiVwimf4newKyq76GUouElGeMT8ibm? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:52:57,591 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:136
2024-07-31 21:53:29,036 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-31 21:53:29,036 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-31 21:53:29,051 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:53:29,521 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:53:30,923 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:129
2024-07-31 21:53:30,927 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1o3QSwnuXZbdJHK2E4iazw7FA5HF4q5sr?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:53:32,647 - INFO - File students.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:141
2024-07-31 21:53:32,647 - INFO - Local file modification time (UTC): 2024-08-01 01:53:32.647142+00:00 - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:149
2024-07-31 21:53:32,662 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1o3QSwnuXZbdJHK2E4iazw7FA5HF4q5sr?fields=modifiedDate&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:53:33,080 - INFO - Google Drive file modification time (UTC): 2024-06-30 17:43:36+00:00 - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:159
2024-07-31 21:53:33,080 - INFO - No need to download. The local file is up-to-date. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:166
2024-07-31 21:53:33,080 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?fields=title&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:53:33,512 - INFO - Original file name: test_name_after_rename - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:176
2024-07-31 21:53:33,518 - DEBUG - URL being requested: PATCH https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?supportsAllDrives=true&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:53:34,437 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1xfdj2ieY3YnIkM9dDcolsBpSo8c-t7rP?fields=title&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:53:34,863 - INFO - File renamed to test_name_after_rename. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:184
2024-07-31 21:53:34,977 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:53:36,326 - INFO - File status.xlsx uploaded to Drive. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:192
2024-07-31 21:53:36,343 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:53:36,780 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:136
2024-07-31 21:55:15,044 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-31 21:55:15,044 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-31 21:55:15,060 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:58:32,227 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-31 21:58:32,244 - INFO - Authentication successful. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-31 21:58:32,244 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:58:32,761 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:58:34,099 - INFO - Lock file created. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:129
2024-07-31 21:58:34,099 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1o3QSwnuXZbdJHK2E4iazw7FA5HF4q5sr?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:58:35,504 - INFO - File data\students.xlsx downloaded. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:141
2024-07-31 21:58:35,504 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:58:35,973 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1kEsXrJGx38-N3ud0bKqvNtbLQ2iNCeqB? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 21:58:36,675 - INFO - Lock file deleted. - c:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:136
2024-07-31 22:04:31,567 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-31 22:04:31,567 - INFO - Authentication successful. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-31 22:04:31,583 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 22:04:32,184 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 22:04:33,573 - INFO - Lock file created. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:129
2024-07-31 22:04:33,589 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1o3QSwnuXZbdJHK2E4iazw7FA5HF4q5sr?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 22:04:35,264 - INFO - File data\students.xlsx downloaded. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:141
2024-07-31 22:04:35,264 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 22:04:35,781 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1G9mN8GPz5-4p9XkL29aYdj2X1BenGnX2? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 22:04:36,436 - INFO - Lock file deleted. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:136
2024-07-31 22:04:48,597 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-31 22:04:48,597 - INFO - Authentication successful. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-31 22:04:48,597 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 22:04:49,168 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 22:04:50,648 - INFO - Lock file created. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:129
2024-07-31 22:04:50,654 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1o3QSwnuXZbdJHK2E4iazw7FA5HF4q5sr?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 22:04:51,958 - INFO - File data\students.xlsx downloaded. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:141
2024-07-31 22:04:51,958 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 22:04:52,479 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1apcRv8kpv2gL8OWgVs-bso6SrfE7u2AL? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 22:04:53,262 - INFO - Lock file deleted. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:136
2024-07-31 22:09:14,332 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-07-31 22:09:14,332 - INFO - Authentication successful. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-07-31 22:09:14,332 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 22:09:14,865 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 22:09:16,153 - INFO - Lock file created. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:129
2024-07-31 22:09:16,168 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1o3QSwnuXZbdJHK2E4iazw7FA5HF4q5sr?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 22:09:17,978 - INFO - File data\students.xlsx downloaded. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:141
2024-07-31 22:09:17,978 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 22:09:18,494 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1zmkc9MlQqXHUTce2irII331JN6lmw0Q-? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-07-31 22:09:19,159 - INFO - Lock file deleted. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:136
2024-08-01 10:34:24,647 - INFO - access_token is expired. Now: 2024-08-01 14:34:24.647955, token_expiry: 2024-08-01 02:52:47 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-08-01 10:34:24,647 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-08-01 10:34:25,116 - INFO - Authentication successful. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-08-01 10:34:25,132 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-08-01 10:34:25,132 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-08-01 10:34:25,718 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-08-01 10:34:27,451 - INFO - Lock file created. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:129
2024-08-01 10:34:27,451 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1o3QSwnuXZbdJHK2E4iazw7FA5HF4q5sr?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-08-01 10:34:29,140 - INFO - File data\students.xlsx downloaded. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:141
2024-08-01 10:34:29,140 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-08-01 10:34:29,672 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1l6vWM-vpjY6orWpHLKtCEchY30rIadNt? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-08-01 10:34:30,505 - INFO - Lock file deleted. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:136
2024-08-04 16:14:06,992 - INFO - access_token is expired. Now: 2024-08-04 20:14:06.992536, token_expiry: 2024-08-01 15:34:24 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:649
2024-08-04 16:14:06,992 - INFO - Refreshing access_token - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\oauth2client\client.py:777
2024-08-04 16:14:07,459 - INFO - Authentication successful. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-08-04 16:14:07,459 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-08-04 16:14:07,475 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-08-04 16:14:07,995 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-08-04 16:14:09,677 - INFO - Lock file created. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:129
2024-08-04 16:14:09,696 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1o3QSwnuXZbdJHK2E4iazw7FA5HF4q5sr?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-08-04 16:14:11,341 - INFO - File data\students.xlsx downloaded. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:141
2024-08-04 16:14:11,341 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-08-04 16:14:12,003 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1ifipGZZIgGvGoJing0aILMfKrk4QBsQ5? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-08-04 16:14:12,759 - INFO - Lock file deleted. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:136
2024-08-04 16:27:21,474 - INFO - file_cache is only supported with oauth2client<4.0.0 - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery_cache\__init__.py:49
2024-08-04 16:27:21,490 - INFO - Authentication successful. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:86
2024-08-04 16:27:21,490 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-08-04 16:27:21,976 - DEBUG - URL being requested: POST https://www.googleapis.com/upload/drive/v2/files?alt=json&uploadType=resumable - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-08-04 16:27:23,592 - INFO - Lock file created. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:129
2024-08-04 16:27:23,592 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files/1o3QSwnuXZbdJHK2E4iazw7FA5HF4q5sr?alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-08-04 16:27:24,824 - INFO - File data\students.xlsx downloaded. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:141
2024-08-04 16:27:24,824 - DEBUG - URL being requested: GET https://www.googleapis.com/drive/v2/files?q=%271hNUQxPSpsArumY0rR8BdcmwmXwHaRTSj%27+in+parents+and+title%3D%27process.lock%27+and+trashed%3Dfalse&maxResults=1000&alt=json - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-08-04 16:27:25,307 - DEBUG - URL being requested: DELETE https://www.googleapis.com/drive/v2/files/1t_j2hCak5gkaUguqpHM7H6BSD-h42rH3? - C:\Users\msenthilnathan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\googleapiclient\discovery.py:1205
2024-08-04 16:27:26,025 - INFO - Lock file deleted. - C:\Users\msenthilnathan\chatGPT-GUI\Nool 2.0\src\gdrive_handler.py:136
